### ISSUE TITLE
What's the meaning of "-DALU" in "mpicc LU_mpi.c -DALU -o par.out"

### ISSUE THREAD

**Issue by yangjixiang** [platipo/MPI-LU-fact#1]
I saw this command "mpicc LU_mpi.c -DALU -o par.out" and had query on what 's the meaning of "DALU"?

**Comment by platipo** [comment]
Hi @yangjixiang, mpicc is based on gcc and takes similar flags: `-D` is used to activate a macro (you can read more in the man on in this [site](https://www.rapidtables.com/code/linux/gcc/gcc-d.html)) for example in [lines 35-39](https://github.com/platipo/MPI-LU-fact/blob/master/LU_mpi.c#L35-L39).
